### ISSUE TITLE
Error: No named parameter with the name 'view'.

### ISSUE THREAD

**Issue by sachindivergents** [ABausG/home_widget#148]
x       view: ui.PlatformDispatcher.instance.implicitView!,
        ^^^^
<img width="1440" alt="Screenshot 2023-07-31 at 5 40 29 PM" src="https://github.com/ABausG/home_widget/assets/113247751/8e8b8dd5-6031-4770-b3e9-4cf7eadb553b">

: Context: Found this candidate, but the arguments don't match.
view.dart:69
  RenderView({
  ^^^^^^^^^^

**Comment by marcelS97** [comment]
You can delete the line 
`view: ui.PlatformDispatcher.instance.implicitView!,`

and replace it with
 `window: ui.PlatformDispatcher.instance.views.first,`

This should fix the problem

**Comment by ABausG** [comment]
This is most likely due to an out of date dart version. Please update and it should work

**Comment by purboindra** [comment]
Hi, i fetch same issue on home_widget: 0.3.0. I'll try to use alpha version home_widget: ^0.4.0-alpha.0 but still not working, the error same. Error log's: 
Error: No named parameter with the name 'view'.
home_widget.dart:142
        view: ui.PlatformDispatcher.instance.implicitView!,
        ^^^^
: Context: Found this candidate, but the arguments don't match.
view.dart:68
  RenderView({
  ^^^^^^^^^^

Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script '/Users/macbook/Documents/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/macbook/Documents/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

<img width="1442" alt="Screenshot 2023-09-15 at 09 51 37" src="https://github.com/ABausG/home_widget/assets/90535981/f336817f-8505-424d-b772-51a662a93d4e">

**Comment by ABausG** [comment]
0.5.0 works on current flutter stable and 0.6.0 with flutter beta (3.20) where the size property changed. Closing this. Please comment again with your flutter doctor outputs and home_widget versions if you still have issues
