### ISSUE TITLE
Getting Run Time Exception on Android 11

### ISSUE THREAD

**Issue by Niranjan-10** [ABausG/home_widget#66]
Fatal Exception: java.lang.RuntimeException: Unable to create service es.antonborri.home_widget.HomeWidgetBackgroundService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4673)
       at android.app.ActivityThread.access$1700(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2196)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by ABausG** [comment]
Could you provide some more information when/how this is happening?

- Does it happen when the user performs an action on the widget?
- What Flutter version are you using? (Looks a bit similar to this issue: https://github.com/transistorsoft/flutter_background_fetch/issues/160

**Comment by Niranjan-10** [comment]
Yeah when app in background user tap on widget it's happening.

**Comment by Niranjan-10** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!

**Comment by Niranjan-10** [comment]
home_widget: ^0.1.3

**Comment by ABausG** [comment]
Is this possible a similar issue as #74 ? If so I would expect that the error message is now different to what you had in the your original issue?

**Comment by ABausG** [comment]
Is this still an issue?

**Comment by harithNasahruddin** [comment]
Im currently having this issue and are not able to fix the problem that is causing the crash. Check my implementation with the documentation I think I have implemented it correctly.

**Comment by firstmetcs** [comment]
Still appears, it seems the exception is due to the call of `HomeWidgetBackgroundIntent.getBroadcast`, when I clicked the title of the example, the flutter app crashes, in the `HomeWidgetExampleProvider` class, the following code deals with the click action of the title section.
```
                val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
                        context,
                        Uri.parse("homeWidgetExample://titleClicked")
                )
                setOnClickPendingIntent(R.id.widget_title, backgroundIntent)
```

/cc @ABausG

**Comment by ABausG** [comment]
@firstmetcs what version of home_widget are you on and which Android Version does this appear with?

i recently build a new example for interactivity using `0.4.0-alpha.0` and did not see any issues with that.
https://medium.com/@ABausG/interactive-homescreen-widgets-with-flutter-using-home-widget-83cb0706a417

**Comment by eliasto** [comment]
Hi! I'm making a contribution about this error.
It seems the crash is encountered when the app is not running in the background. Therefore, the widget cannot communicate with the dart code, so the crash. I don't know if there is a way to force the opening of the app in the background ? Because, for example, when the user update the app on the Google Play Store, and add the widget on the home screen, without opening the app first, the crash will occur.
Nevertheless, this crash won't happen if the app was opened, before the installation of the widget.
Here, some crashlytics logs from a random device.
Thank you for your help. :)
[Crashlytics_home_widget.txt](https://github.com/ABausG/home_widget/files/12918518/Crashlytics_home_widget.txt)
